"""
Report Synthesizer — Takes all research content collected by the agent
and generates a structured, well-written report via an LLM chain.

Output: a fully populated Report Pydantic model with:
  - Executive summary
  - Key findings (bullet list)
  - Detailed analysis (multi-paragraph)
  - Follow-up questions
  - Full markdown document
  - Cited sources
"""

import os
import uuid
import json
from datetime import datetime
from typing import List

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser

from models.schemas import Report, Source, ReportDepth


# ─── Prompts ──────────────────────────────────────────────────────────────────

SYNTHESIS_PROMPT = ChatPromptTemplate.from_messages([
    ("system", """You are an expert research analyst and technical writer.
Your job is to synthesize raw research content into a clear, structured, insightful report.

You will be given:
- A research topic
- Raw content collected from web searches, articles, and academic papers
- A list of sources

You must produce a JSON object with EXACTLY these fields:
{{
  "executive_summary": "2-3 paragraph high-level summary of the entire topic",
  "key_findings": ["finding 1", "finding 2", "finding 3", "finding 4", "finding 5"],
  "detailed_analysis": "4-6 paragraphs of deep analysis covering trends, implications, challenges, and opportunities",
  "follow_up_questions": ["question 1", "question 2", "question 3"]
}}

Rules:
- Be factual and grounded in the provided content
- Use specific data points, statistics, and dates when available
- key_findings must be concrete and specific — not vague generalities
- detailed_analysis must have clear paragraph breaks using \\n\\n
- follow_up_questions should spark further research
- Do not make up information not present in the content
- Return ONLY valid JSON, no markdown fences"""),

    ("human", """RESEARCH TOPIC: {topic}

RAW RESEARCH CONTENT:
{content}

SOURCES USED:
{sources_summary}

Generate the structured report JSON now:""")
])


MARKDOWN_PROMPT = ChatPromptTemplate.from_messages([
    ("system", """You are a professional technical writer.
Convert the provided structured report data into a beautiful, well-formatted Markdown document.

The document must include these sections in order:
1. # Title (the topic)
2. ## Executive Summary
3. ## Key Findings (as a bullet list)
4. ## Detailed Analysis
5. ## Follow-up Questions (as numbered list)
6. ## Sources (as a numbered list with links where available)
7. ---
8. *Generated by Autonomous Research Agent on {date}*

Use proper Markdown: headers, bold for emphasis, bullet points, horizontal rules.
Return ONLY the raw Markdown text."""),

    ("human", """TOPIC: {topic}

EXECUTIVE SUMMARY:
{executive_summary}

KEY FINDINGS:
{key_findings}

DETAILED ANALYSIS:
{detailed_analysis}

FOLLOW-UP QUESTIONS:
{follow_up_questions}

SOURCES:
{sources_text}""")
])


# ─── Synthesizer Class ────────────────────────────────────────────────────────

class ReportSynthesizer:
    """
    Two-stage LLM chain:
      Stage 1 → Structured JSON extraction (analysis chain)
      Stage 2 → Markdown document generation (markdown chain)
    """

    def __init__(self):
        # Use Gemini 2.0 Flash for synthesis quality
        self._llm = ChatGoogleGenerativeAI(
            model="gemini-2.0-flash",
            temperature=0.3,
            google_api_key=os.getenv("GOOGLE_API_KEY"),
        )
        self._parser = StrOutputParser()
        self._analysis_chain = SYNTHESIS_PROMPT | self._llm | self._parser
        self._markdown_chain = MARKDOWN_PROMPT | self._llm | self._parser

    def synthesize(
        self,
        topic: str,
        depth: ReportDepth,
        content_chunks: List[str],
        sources: List[Source],
    ) -> Report:
        """
        Main entry point. Takes raw gathered content and produces a Report.
        """
        # Combine all content chunks into one context block
        combined_content = self._prepare_content(content_chunks)
        sources_summary = self._summarize_sources(sources)

        # ── Stage 1: Structured analysis ──────────────────────────────────────
        raw_json = self._analysis_chain.invoke({
            "topic": topic,
            "content": combined_content,
            "sources_summary": sources_summary,
        })

        parsed = self._parse_json_safely(raw_json)

        executive_summary    = parsed.get("executive_summary", "Summary not available.")
        key_findings         = parsed.get("key_findings", [])
        detailed_analysis    = parsed.get("detailed_analysis", "Analysis not available.")
        follow_up_questions  = parsed.get("follow_up_questions", [])

        # ── Stage 2: Markdown document ────────────────────────────────────────
        sources_text = self._format_sources_for_markdown(sources)
        key_findings_text = "\n".join(f"- {f}" for f in key_findings)
        fq_text = "\n".join(f"{i+1}. {q}" for i, q in enumerate(follow_up_questions))

        full_markdown = self._markdown_chain.invoke({
            "topic": topic,
            "executive_summary": executive_summary,
            "key_findings": key_findings_text,
            "detailed_analysis": detailed_analysis,
            "follow_up_questions": fq_text,
            "sources_text": sources_text,
            "date": datetime.utcnow().strftime("%B %d, %Y"),
        })

        # ── Assemble final Report ─────────────────────────────────────────────
        return Report(
            id=str(uuid.uuid4()),
            topic=topic,
            depth=depth,
            executive_summary=executive_summary,
            key_findings=key_findings if isinstance(key_findings, list) else [],
            detailed_analysis=detailed_analysis,
            follow_up_questions=follow_up_questions if isinstance(follow_up_questions, list) else [],
            sources=sources,
            full_markdown=full_markdown,
        )

    # ─── Helpers ──────────────────────────────────────────────────────────────

    def _prepare_content(self, chunks: List[str]) -> str:
        """Join content chunks with clear separators, truncated to ~12k chars."""
        if not chunks:
            return "No content gathered."
        joined = "\n\n---\n\n".join(c.strip() for c in chunks if c.strip())
        # Keep within a safe context window
        return joined[:12000] + ("..." if len(joined) > 12000 else "")

    def _summarize_sources(self, sources: List[Source]) -> str:
        if not sources:
            return "No sources."
        lines = []
        for i, s in enumerate(sources, 1):
            url_part = f" ({s.url})" if s.url else ""
            lines.append(f"{i}. [{s.source_type.upper()}] {s.title}{url_part}")
        return "\n".join(lines)

    def _format_sources_for_markdown(self, sources: List[Source]) -> str:
        if not sources:
            return "No sources available."
        lines = []
        for i, s in enumerate(sources, 1):
            if s.url:
                lines.append(f"{i}. [{s.title}]({s.url}) — *{s.source_type}*")
            else:
                lines.append(f"{i}. {s.title} — *{s.source_type}*")
        return "\n".join(lines)

    def _parse_json_safely(self, raw: str) -> dict:
        """Robustly parse JSON from LLM output, handling common formatting issues."""
        text = raw.strip()
        # Strip markdown code fences if present
        if text.startswith("```"):
            lines = text.splitlines()
            text = "\n".join(lines[1:-1] if lines[-1].strip() == "```" else lines[1:])
        try:
            return json.loads(text)
        except json.JSONDecodeError:
            # Attempt to extract JSON object with brute-force bracket matching
            start = text.find("{")
            end   = text.rfind("}") + 1
            if start != -1 and end > start:
                try:
                    return json.loads(text[start:end])
                except json.JSONDecodeError:
                    pass
        return {}
